### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by slunak** [moneyphp/crypto-currencies#1]
@frederikbosch hey, I am starting to move the code. I would like to clarify naming conventions.

1. Namespace. Currently it is `Serhiy\Cryptocurrencies`. I think it better to have a namespace similar to `MoneyPHP\CryptoCurrencies`. But there is additional clarification I would like to make. Cryptocurrencies is actually one word and therefore `MoneyPHP\Cryptocurrencies` would the correct namespace to use, however it does not go well with the repo name `crypto-currencies` and the other ISOCurrency library.
2. Package name. Currently it is `serhiy/cryptocurrencies-money-php`. Should I name it `moneyphp/crypto-currencies` or `moneyphp/cryptocurrencies` and then you can make it available via composer?
 
Please let me know your decisions on both points and I will then prepare and move the code.

**Comment by frederikbosch** [comment]
@slunak Great question.

1. Let's go for `MoneyPHP\CryptoCurrencies`.
2. And then also for `moneyphp/crypto-currencies`.

**Comment by slunak** [comment]
@frederikbosch the code has been moved. I also created a first release. Would you be able to make it available via composer please?

**Comment by slunak** [comment]
@frederikbosch, is there anything else I can do for the repository?

**Comment by frederikbosch** [comment]
Sorry, quite busy, will finish it this week. Maybe I need some help from Mark too, which could cause some delay.

**Comment by slunak** [comment]
Now worries, let me know if anything.
